### ISSUE TITLE
Archer is depending on an obsolete version of Sami

### ISSUE THREAD

**Issue by redbeardcreator** [IcecaveStudios/archer#103]
Version 1.1.0 of [Sami](https://packagist.org/packages/sami/sami) is dependent on [dflydev/markdown](https://packagist.org/packages/dflydev/markdown), which is marked as abandoned and replaced by [michelf/php-markdown](https://packagist.org/packages/michelf/php-markdown). The current version of Sami is 2.0.0. The first version of Sami that included the updated dependency was 1.3.

**Comment by jmalloc** [comment]
Sami is now at ~3

**Comment by jmalloc** [comment]
Fixed in v1.3.2
