### ISSUE TITLE
Use `sudo: false` in all .travis.yml for faster builds

### ISSUE THREAD

**Issue by ezzatron** [IcecaveStudios/archer#109]

**Comment by jmalloc** [comment]
Is this related to this http://docs.travis-ci.com/user/workers/container-based-infrastructure/ ?
`sudo : false` seems like an unusual way to communicate it?

**Comment by ezzatron** [comment]
That is what I'm talking about. I think they probably plan to use that new infrastructure for everything by default, eventually. One of its limitations is the fact that sudo is unavailable. I guess sudo was previously available by default, so this just indicates that your build process is compatible.

**Comment by jmalloc** [comment]
Ah right, that makes more sense (y)
