### ISSUE TITLE
Improve Travis CI configuration generation.

### ISSUE THREAD

**Issue by jmalloc** [IcecaveStudios/archer#85]
@ezzatron

It's becoming problematic to just have archer blow away the Travis config. I have been considering making `archer update` on regen the travis config if it's not already present, or if a particular flag is passed, such that it's more like a template than something archer maintains ongoing.

I think we probably also need a better system than a text template for storing this in Archer's own resources, maybe even generate it entirely programatically.

**Comment by ezzatron** [comment]
Is there anything more we need to do here? It already handles "unstable" versions (7.0) and "alternate" versions (hhvm). If we need something more specific, we can open another ticket.
